CREATE TABLE IF F NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);
ALTER TABLE students 
ADD COLUMN IF NOT EXISTS exam_score INTEGER;
ALTER TABLE students 
ADD COLUMN IF NOT EXISTS direction VARCHAR(100);